# SwiftLint configuration
# Rules reference: https://realm.github.io/SwiftLint/rule-directory.html

included:
  - TicTacToe
  - TicTacToeTests
  - TicTacToeUITests

excluded:
  - DerivedData
  - build

opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_first_not_nil
  - empty_count
  - empty_string
  - explicit_init
  - fatal_error_message
  - first_where
  - force_unwrapping
  - identical_operands
  - implicitly_unwrapped_optional
  - last_where
  - modifier_order
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - sorted_first_last
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - yoda_condition

line_length:
  warning: 120
  error: 160
  ignores_urls: true

identifier_name:
  excluded:
    - id
    - x
    - y

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 800
